//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkdownMode {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MarkdownMode.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _301 {
            get {
                object obj = ResourceManager.GetObject("301", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create tool window..
        /// </summary>
        internal static string CanNotCreateWindow {
            get {
                return ResourceManager.GetString("CanNotCreateWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown Block.
        /// </summary>
        internal static string FormatBlock {
            get {
                return ResourceManager.GetString("FormatBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown Block Quote.
        /// </summary>
        internal static string FormatBlockQuote {
            get {
                return ResourceManager.GetString("FormatBlockQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown Bold.
        /// </summary>
        internal static string FormatBold {
            get {
                return ResourceManager.GetString("FormatBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown Header.
        /// </summary>
        internal static string FormatHeader {
            get {
                return ResourceManager.GetString("FormatHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown Header (Level 1).
        /// </summary>
        internal static string FormatHeaderH1 {
            get {
                return ResourceManager.GetString("FormatHeaderH1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown Header (Level 2).
        /// </summary>
        internal static string FormatHeaderH2 {
            get {
                return ResourceManager.GetString("FormatHeaderH2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown Header (Level 3).
        /// </summary>
        internal static string FormatHeaderH3 {
            get {
                return ResourceManager.GetString("FormatHeaderH3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown Header (Level 4).
        /// </summary>
        internal static string FormatHeaderH4 {
            get {
                return ResourceManager.GetString("FormatHeaderH4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown Header (Level 5).
        /// </summary>
        internal static string FormatHeaderH5 {
            get {
                return ResourceManager.GetString("FormatHeaderH5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown Header (Level 6).
        /// </summary>
        internal static string FormatHeaderH6 {
            get {
                return ResourceManager.GetString("FormatHeaderH6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown Horizonal Rule.
        /// </summary>
        internal static string FormatHorizontalRule {
            get {
                return ResourceManager.GetString("FormatHorizontalRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown Image.
        /// </summary>
        internal static string FormatImage {
            get {
                return ResourceManager.GetString("FormatImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown Image (Alt Text).
        /// </summary>
        internal static string FormatImageAlt {
            get {
                return ResourceManager.GetString("FormatImageAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown Image (Label).
        /// </summary>
        internal static string FormatImageLabel {
            get {
                return ResourceManager.GetString("FormatImageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown Image (Title).
        /// </summary>
        internal static string FormatImageTitle {
            get {
                return ResourceManager.GetString("FormatImageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown Italics.
        /// </summary>
        internal static string FormatItalics {
            get {
                return ResourceManager.GetString("FormatItalics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown Link.
        /// </summary>
        internal static string FormatLink {
            get {
                return ResourceManager.GetString("FormatLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown Link (Label).
        /// </summary>
        internal static string FormatLinkLabel {
            get {
                return ResourceManager.GetString("FormatLinkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown Link (Text).
        /// </summary>
        internal static string FormatLinkText {
            get {
                return ResourceManager.GetString("FormatLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown Link (Title).
        /// </summary>
        internal static string FormatLinkTitle {
            get {
                return ResourceManager.GetString("FormatLinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown List.
        /// </summary>
        internal static string FormatList {
            get {
                return ResourceManager.GetString("FormatList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown Preformatted.
        /// </summary>
        internal static string FormatPre {
            get {
                return ResourceManager.GetString("FormatPre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown URL.
        /// </summary>
        internal static string FormatUrl {
            get {
                return ResourceManager.GetString("FormatUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown Preview Window.
        /// </summary>
        internal static string ToolWindowTitle {
            get {
                return ResourceManager.GetString("ToolWindowTitle", resourceCulture);
            }
        }
    }
}
